version: '3.9'

services:
  whisper-api:
    image: "spbiffi/whisper-api:latest"
    container_name: "whisper-api"
    restart: on-failure
    ports:
      - "9099:9099"
    env_file:
      - .env
    volumes:
      - "${DOCKER_VOLUMES}/whisper-api:/app/data"  # если нужно монтировать папку с данными внутрь контейнера (можно убрать если не надо)
    networks:
      - shared_network

networks:
  shared_network:
    external: true

